//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAODLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BanAn
    {
        public string MaBanAn { get; set; }
        public string MaKhuVuc { get; set; }
        public string MaPhieuDat { get; set; }
        public string MaLoaiBan { get; set; }
        public string TinhTrang { get; set; }
    
        public virtual PhieuDatBan PhieuDatBan { get; set; }
        public virtual KhuVuc KhuVuc { get; set; }
        public virtual LoaiBan LoaiBan { get; set; }
    }
}
