//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAODLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietPN
    {
        public string MaNL { get; set; }
        public string MaPhieuNhap { get; set; }
        public System.DateTime ngaynhap { get; set; }
        public Nullable<int> SoLuongNhap { get; set; }
        public Nullable<decimal> DonGiaNhap { get; set; }
    
        public virtual NguyenLieu NguyenLieu { get; set; }
        public virtual PhieuNhap PhieuNhap { get; set; }
    }
}
