//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAODLL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class NhaHangDoriEntities : DbContext
    {
        public NhaHangDoriEntities()
            : base("name=NhaHangDoriEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BanAn> BanAns { get; set; }
        public virtual DbSet<ChiTietKH> ChiTietKHs { get; set; }
        public virtual DbSet<ChiTietPN> ChiTietPNs { get; set; }
        public virtual DbSet<HoaDon> HoaDons { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<KhuVuc> KhuVucs { get; set; }
        public virtual DbSet<LoaiBan> LoaiBans { get; set; }
        public virtual DbSet<ManHinh> ManHinhs { get; set; }
        public virtual DbSet<MonAn> MonAns { get; set; }
        public virtual DbSet<NguoiDung> NguoiDungs { get; set; }
        public virtual DbSet<NguoiDungNhomNguoiDung> NguoiDungNhomNguoiDungs { get; set; }
        public virtual DbSet<NguyenLieu> NguyenLieux { get; set; }
        public virtual DbSet<NhaCungCap> NhaCungCaps { get; set; }
        public virtual DbSet<Nhan_Vien> Nhan_Vien { get; set; }
        public virtual DbSet<NhomMonAn> NhomMonAns { get; set; }
        public virtual DbSet<NhomNguoiDung> NhomNguoiDungs { get; set; }
        public virtual DbSet<NhomNguyenLieu> NhomNguyenLieux { get; set; }
        public virtual DbSet<PhanQuyen> PhanQuyens { get; set; }
        public virtual DbSet<PhieuDatBan> PhieuDatBans { get; set; }
        public virtual DbSet<PhieuNhap> PhieuNhaps { get; set; }
        public virtual DbSet<SoLuongMonAn> SoLuongMonAns { get; set; }
        public virtual DbSet<TenLoaiKhach> TenLoaiKhaches { get; set; }
    
        public virtual ObjectResult<vc_user_Result> vc_user()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<vc_user_Result>("vc_user");
        }
    }
}
