//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAODLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public string MaHD { get; set; }
        public string MaPhieuDat { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public Nullable<decimal> TongTienHD { get; set; }
        public Nullable<double> VAT { get; set; }
        public Nullable<decimal> ThanhToan { get; set; }
        public string Ma_nv { get; set; }
    
        public virtual Nhan_Vien Nhan_Vien { get; set; }
        public virtual PhieuDatBan PhieuDatBan { get; set; }
    }
}
