//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAODLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonAn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MonAn()
        {
            this.SoLuongMonAns = new HashSet<SoLuongMonAn>();
            this.NguyenLieux = new HashSet<NguyenLieu>();
        }
    
        public string MaMonAn { get; set; }
        public string MaNhomMA { get; set; }
        public string TenMonAn { get; set; }
        public string MaNL { get; set; }
        public Nullable<decimal> DonGiaMonAn { get; set; }
        public string DonViTinh { get; set; }
        public byte[] Hinh { get; set; }
    
        public virtual NhomMonAn NhomMonAn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoLuongMonAn> SoLuongMonAns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NguyenLieu> NguyenLieux { get; set; }
    }
}
