//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAODLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanQuyen
    {
        public string MaNhomNguoiDung { get; set; }
        public string MaManHinh { get; set; }
        public bool CoQuyen { get; set; }
    
        public virtual ManHinh ManHinh { get; set; }
        public virtual NhomNguoiDung NhomNguoiDung { get; set; }
    }
}
