//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAODLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoLuongMonAn
    {
        public string MaMonAn { get; set; }
        public string MaPhieuDat { get; set; }
        public Nullable<int> SoLuongMA { get; set; }
    
        public virtual MonAn MonAn { get; set; }
        public virtual PhieuDatBan PhieuDatBan { get; set; }
    }
}
